version: '3'

services:
  db:
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "docker-root"
  frontend:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: dockerfiles/vuejs
    depends_on:
      -  backend
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./src/frontend:/opt/frontend
    environment:
      - HOST=0.0.0.0
      - PORT=${FRONTEND_PORT}
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=${BACKEND_RUNNING_ON}
      - API_PORT=${BACKEND_PORT}
  backend:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: dockerfiles/backend
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./src/backend:/opt/backend
    environment:
      - PYTHONPATH=/opt/backend
      - DJANGO_SETTINGS_MODULE=api.settings
      - FRONTEND_PORT=${FRONTEND_PORT}
      - POSTGRES_DB=docker
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=docker-root
  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=secret
