# Generated by Django 4.0.6 on 2022-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Address', models.CharField(max_length=10)),
                ('User_Comment', models.CharField(max_length=300)),
                ('User_Comment_Tread', models.CharField(max_length=1)),
                ('User_Comment_Praise', models.CharField(max_length=1)),
            ],
        ),
    ]
