# Generated by Django 4.0.6 on 2022-07-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_address_secret_praise_tread_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='address_secret',
            new_name='AddressSecret',
        ),
        migrations.RenameModel(
            old_name='message',
            new_name='GetMessage',
        ),
        migrations.RenameModel(
            old_name='praise_tread',
            new_name='PraiseTread',
        ),
    ]
