# Generated by Django 4.0.6 on 2022-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_address_secret_addresssecret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getmessage',
            name='Comment_Bool',
            field=models.BooleanField(default=True),
        ),
    ]
